### ISSUE TITLE
Found Source Files For Noisli

### ISSUE THREAD

**Issue by dvdcd** [brunobord/relax#12]
Rain: https://s3.amazonaws.com/noisliaudio/rain.ogg
Thunderstorm: https://s3.amazonaws.com/noisliaudio/thunderstorm.ogg
Wind: https://s3.amazonaws.com/noisliaudio/wind.ogg
Forest: https://s3.amazonaws.com/noisliaudio/forest.ogg
Leaves: https://s3.amazonaws.com/noisliaudio/leaves.ogg
Stream: https://s3.amazonaws.com/noisliaudio/waterstream.ogg
Seaside: https://s3.amazonaws.com/noisliaudio/seaside.ogg
Water: https://s3.amazonaws.com/noisliaudio/water.ogg
Fire: https://s3.amazonaws.com/noisliaudio/fire.ogg
Summer Nights: https://s3.amazonaws.com/noisliaudio/summernight.ogg
Cafe: https://s3.amazonaws.com/noisliaudio/coffee.ogg
Train: https://s3.amazonaws.com/noisliaudio/train.ogg
Fan: https://s3.amazonaws.com/noisliaudio/fan.ogg
"White" Noise: https://s3.amazonaws.com/noisliaudio/whitenoise.ogg
"Pink" Noise: https://s3.amazonaws.com/noisliaudio/pinknoise.ogg
"Brown" Noise: https://s3.amazonaws.com/noisliaudio/brownnoise.ogg

**Comment by brunobord** [comment]
Hi there: the Relax project is a rip-off of Noisli, but even if I appreciate your will to help, I cannot use these.

Before publishing this project, I've asked permission to the author of Noisli, and he told me he was okay with this open-source version to condition that I wouldn't infringe his intellectual property. Icons, layout **and sounds** cannot be used without permission on this project.
I agree this is 100% legit: using the noisli.com sounds would be copyright violation.

This project would only use Free (as in Free Speech) sounds and icons.

Thank you again for your help.

**Comment by dvdcd** [comment]
Ah ok. Did not think of copyrights when i grabbed these. also its nice your still around on a 3 y/o project!
