### ISSUE TITLE
No sound in Safari 14.0.1 on MacOS 10.15.7

### ISSUE THREAD

**Issue by BrendanTWhite** [brunobord/relax#14]
No actual sound plays in Safari 14.0.1 on MacOS 10.15.7. This can be fixed by upgrading jPlayer to 2.9.2. I'll do a pull request.

**Comment by BrendanTWhite** [comment]
Sound works just fine in Chrome on my Mac.  

I haven't tried other browsers, or other operating systems.

**Comment by brunobord** [comment]
closed with #15
